[DEV-1984] Create schools_updater.yml
MLH/mlh-policies pull request #230
Opened 2024-10-25 13:58 UTC by yodarjun

This script does the following:
1.Fetch a JSON object from the schools API endpoint using credentials.
2.Convert the JSON response into a CSV file.
3.Commit and push the updated CSV file back to the repository.

2024-10-28 14:32 UTC, erinosher requested changes
Updated to run on your dev branch. Looks fine other than the commit/push step isn't working. Made some suggestions that _should_ fix it.

2024-10-28 14:32 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +          git add path/to/your/output.csv
```suggestion
          git add schools.csv
```

2024-10-28 14:32 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +      - name: Commit and push CSV file
```suggestion
      - name: Commit CSV file
```

2024-10-28 14:32 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +
Remove before merging.

```suggestion

```

2024-10-29 16:54 UTC, erinosher requested changes

2024-10-29 16:54 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +          in2csv data.json > schools.csv
We only actually care about the name column, particularly given the size of the CSV.

2024-10-29 16:54 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +            RESPONSE=$(curl -s -H "Authorization: Bearer $API_TOKEN" "$API_URL?page=$PAGE&limit=$LIMIT")
needs to use the `verified[eq]=true` filter, I tried updating it, but it errored for me for some reason.

2024-10-29 16:54 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +
Leaving this as aa_schools_csv_updater for now as we want to ensure this is working before it hits main

2024-10-31 13:10 UTC, yodarjun commented on .github/workflows/schools_updater.yml
> +          git commit -m "Update CSV file from API data [skip ci]"
the `skip ci` basically tells github actions that it doesnt have to run any checks for this commit

2024-10-31 13:31 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +          git commit -m "Update CSV file from API data [skip ci]"
Oh, that shouldn't matter here b/c the commit is on the `GITHUB_TOKEN` so it [won't trigger anyway.](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)

2024-11-12 16:56 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +          git push
```suggestion
        run: |
          # Configure git
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Commit and push changes
          git add schools.csv
          git commit -m "Update schools CSV file from API data [skip ci]"
          git push
```

2024-11-12 17:00 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +          jq -r '.[].name' data.json > schools.csv
```suggestion
        run: |
          # Add first line to CSV file
          echo "\"Below is a list of all schools that we've manually verified. If you see one that hasn't been included, please add it via my.mlh.io and we'll verify it soon.\"" > schools.csv
          
          # Extract only the "name" field from each entry and overwrite data.json
          jq -r '.[].name' data.json >> schools.csv
```

2024-11-12 17:46 UTC, erinosher approved these changes

2024-11-12 17:46 UTC, erinosher commented on .github/workflows/schools_updater.yml
> +      - aa_schools_csv_updater
```suggestion
      - main
```

2024-11-12 17:47 UTC, merged